// I am a noob programmer. I only can write a stupid and verbose code ;(

void turnOffAll(){
  digitalWrite(12, LOW);
  digitalWrite(14, LOW);
  digitalWrite(27, LOW);
  digitalWrite(26, LOW);
  digitalWrite(25, LOW);
  digitalWrite(33, LOW);
  digitalWrite(32, LOW);
  digitalWrite(23, LOW);
}

void setup() {
  pinMode(12, OUTPUT);
  pinMode(14, OUTPUT);
  pinMode(27, OUTPUT);
  pinMode(26, OUTPUT);
  pinMode(25, OUTPUT);
  pinMode(33, OUTPUT);
  pinMode(32, OUTPUT);
  pinMode(23, OUTPUT);
}

void loop() {
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(12, HIGH);
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  delay(1000);
  turnOffAll();
  digitalWrite(14, HIGH);
  digitalWrite(27, HIGH);
  digitalWrite(25, HIGH);
  digitalWrite(33, HIGH);
  digitalWrite(32, HIGH);
  digitalWrite(23, HIGH);
  delay(1000);
}

// If you live in Japan, you can print a diagram:)
